/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.berkeley.sparrow.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TResourceUsage implements org.apache.thrift.TBase<TResourceUsage, TResourceUsage._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TResourceUsage");

  private static final org.apache.thrift.protocol.TField RESOURCES_FIELD_DESC = new org.apache.thrift.protocol.TField("resources", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField QUEUE_LENGTH_FIELD_DESC = new org.apache.thrift.protocol.TField("queueLength", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField SCALED_QUEUE_LENGTH_FIELD_DESC = new org.apache.thrift.protocol.TField("scaledQueueLength", org.apache.thrift.protocol.TType.DOUBLE, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TResourceUsageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TResourceUsageTupleSchemeFactory());
  }

  public TResourceVector resources; // required
  public int queueLength; // required
  public double scaledQueueLength; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESOURCES((short)1, "resources"),
    QUEUE_LENGTH((short)2, "queueLength"),
    SCALED_QUEUE_LENGTH((short)3, "scaledQueueLength");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESOURCES
          return RESOURCES;
        case 2: // QUEUE_LENGTH
          return QUEUE_LENGTH;
        case 3: // SCALED_QUEUE_LENGTH
          return SCALED_QUEUE_LENGTH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __QUEUELENGTH_ISSET_ID = 0;
  private static final int __SCALEDQUEUELENGTH_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.SCALED_QUEUE_LENGTH};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESOURCES, new org.apache.thrift.meta_data.FieldMetaData("resources", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TResourceVector.class)));
    tmpMap.put(_Fields.QUEUE_LENGTH, new org.apache.thrift.meta_data.FieldMetaData("queueLength", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SCALED_QUEUE_LENGTH, new org.apache.thrift.meta_data.FieldMetaData("scaledQueueLength", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TResourceUsage.class, metaDataMap);
  }

  public TResourceUsage() {
  }

  public TResourceUsage(
    TResourceVector resources,
    int queueLength)
  {
    this();
    this.resources = resources;
    this.queueLength = queueLength;
    setQueueLengthIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TResourceUsage(TResourceUsage other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetResources()) {
      this.resources = new TResourceVector(other.resources);
    }
    this.queueLength = other.queueLength;
    this.scaledQueueLength = other.scaledQueueLength;
  }

  public TResourceUsage deepCopy() {
    return new TResourceUsage(this);
  }

  public void clear() {
    this.resources = null;
    setQueueLengthIsSet(false);
    this.queueLength = 0;
    setScaledQueueLengthIsSet(false);
    this.scaledQueueLength = 0.0;
  }

  public TResourceVector getResources() {
    return this.resources;
  }

  public TResourceUsage setResources(TResourceVector resources) {
    this.resources = resources;
    return this;
  }

  public void unsetResources() {
    this.resources = null;
  }

  /** Returns true if field resources is set (has been assigned a value) and false otherwise */
  public boolean isSetResources() {
    return this.resources != null;
  }

  public void setResourcesIsSet(boolean value) {
    if (!value) {
      this.resources = null;
    }
  }

  public int getQueueLength() {
    return this.queueLength;
  }

  public TResourceUsage setQueueLength(int queueLength) {
    this.queueLength = queueLength;
    setQueueLengthIsSet(true);
    return this;
  }

  public void unsetQueueLength() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __QUEUELENGTH_ISSET_ID);
  }

  /** Returns true if field queueLength is set (has been assigned a value) and false otherwise */
  public boolean isSetQueueLength() {
    return EncodingUtils.testBit(__isset_bitfield, __QUEUELENGTH_ISSET_ID);
  }

  public void setQueueLengthIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __QUEUELENGTH_ISSET_ID, value);
  }

  public double getScaledQueueLength() {
    return this.scaledQueueLength;
  }

  public TResourceUsage setScaledQueueLength(double scaledQueueLength) {
    this.scaledQueueLength = scaledQueueLength;
    setScaledQueueLengthIsSet(true);
    return this;
  }

  public void unsetScaledQueueLength() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SCALEDQUEUELENGTH_ISSET_ID);
  }

  /** Returns true if field scaledQueueLength is set (has been assigned a value) and false otherwise */
  public boolean isSetScaledQueueLength() {
    return EncodingUtils.testBit(__isset_bitfield, __SCALEDQUEUELENGTH_ISSET_ID);
  }

  public void setScaledQueueLengthIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SCALEDQUEUELENGTH_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESOURCES:
      if (value == null) {
        unsetResources();
      } else {
        setResources((TResourceVector)value);
      }
      break;

    case QUEUE_LENGTH:
      if (value == null) {
        unsetQueueLength();
      } else {
        setQueueLength((Integer)value);
      }
      break;

    case SCALED_QUEUE_LENGTH:
      if (value == null) {
        unsetScaledQueueLength();
      } else {
        setScaledQueueLength((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESOURCES:
      return getResources();

    case QUEUE_LENGTH:
      return Integer.valueOf(getQueueLength());

    case SCALED_QUEUE_LENGTH:
      return Double.valueOf(getScaledQueueLength());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESOURCES:
      return isSetResources();
    case QUEUE_LENGTH:
      return isSetQueueLength();
    case SCALED_QUEUE_LENGTH:
      return isSetScaledQueueLength();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TResourceUsage)
      return this.equals((TResourceUsage)that);
    return false;
  }

  public boolean equals(TResourceUsage that) {
    if (that == null)
      return false;

    boolean this_present_resources = true && this.isSetResources();
    boolean that_present_resources = true && that.isSetResources();
    if (this_present_resources || that_present_resources) {
      if (!(this_present_resources && that_present_resources))
        return false;
      if (!this.resources.equals(that.resources))
        return false;
    }

    boolean this_present_queueLength = true;
    boolean that_present_queueLength = true;
    if (this_present_queueLength || that_present_queueLength) {
      if (!(this_present_queueLength && that_present_queueLength))
        return false;
      if (this.queueLength != that.queueLength)
        return false;
    }

    boolean this_present_scaledQueueLength = true && this.isSetScaledQueueLength();
    boolean that_present_scaledQueueLength = true && that.isSetScaledQueueLength();
    if (this_present_scaledQueueLength || that_present_scaledQueueLength) {
      if (!(this_present_scaledQueueLength && that_present_scaledQueueLength))
        return false;
      if (this.scaledQueueLength != that.scaledQueueLength)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TResourceUsage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TResourceUsage typedOther = (TResourceUsage)other;

    lastComparison = Boolean.valueOf(isSetResources()).compareTo(typedOther.isSetResources());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResources()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resources, typedOther.resources);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQueueLength()).compareTo(typedOther.isSetQueueLength());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQueueLength()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.queueLength, typedOther.queueLength);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetScaledQueueLength()).compareTo(typedOther.isSetScaledQueueLength());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScaledQueueLength()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scaledQueueLength, typedOther.scaledQueueLength);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TResourceUsage(");
    boolean first = true;

    sb.append("resources:");
    if (this.resources == null) {
      sb.append("null");
    } else {
      sb.append(this.resources);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("queueLength:");
    sb.append(this.queueLength);
    first = false;
    if (isSetScaledQueueLength()) {
      if (!first) sb.append(", ");
      sb.append("scaledQueueLength:");
      sb.append(this.scaledQueueLength);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (resources != null) {
      resources.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private static class TResourceUsageStandardSchemeFactory implements SchemeFactory {
    public TResourceUsageStandardScheme getScheme() {
      return new TResourceUsageStandardScheme();
    }
  }

  private static class TResourceUsageStandardScheme extends StandardScheme<TResourceUsage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TResourceUsage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESOURCES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.resources = new TResourceVector();
              struct.resources.read(iprot);
              struct.setResourcesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // QUEUE_LENGTH
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.queueLength = iprot.readI32();
              struct.setQueueLengthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SCALED_QUEUE_LENGTH
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.scaledQueueLength = iprot.readDouble();
              struct.setScaledQueueLengthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TResourceUsage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.resources != null) {
        oprot.writeFieldBegin(RESOURCES_FIELD_DESC);
        struct.resources.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(QUEUE_LENGTH_FIELD_DESC);
      oprot.writeI32(struct.queueLength);
      oprot.writeFieldEnd();
      if (struct.isSetScaledQueueLength()) {
        oprot.writeFieldBegin(SCALED_QUEUE_LENGTH_FIELD_DESC);
        oprot.writeDouble(struct.scaledQueueLength);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TResourceUsageTupleSchemeFactory implements SchemeFactory {
    public TResourceUsageTupleScheme getScheme() {
      return new TResourceUsageTupleScheme();
    }
  }

  private static class TResourceUsageTupleScheme extends TupleScheme<TResourceUsage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TResourceUsage struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetResources()) {
        optionals.set(0);
      }
      if (struct.isSetQueueLength()) {
        optionals.set(1);
      }
      if (struct.isSetScaledQueueLength()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetResources()) {
        struct.resources.write(oprot);
      }
      if (struct.isSetQueueLength()) {
        oprot.writeI32(struct.queueLength);
      }
      if (struct.isSetScaledQueueLength()) {
        oprot.writeDouble(struct.scaledQueueLength);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TResourceUsage struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.resources = new TResourceVector();
        struct.resources.read(iprot);
        struct.setResourcesIsSet(true);
      }
      if (incoming.get(1)) {
        struct.queueLength = iprot.readI32();
        struct.setQueueLengthIsSet(true);
      }
      if (incoming.get(2)) {
        struct.scaledQueueLength = iprot.readDouble();
        struct.setScaledQueueLengthIsSet(true);
      }
    }
  }

}

